# Generated by Django 4.1.7 on 2023-02-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nom_classe', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('nom_model', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id_histo', models.AutoField(primary_key=True, serialize=False)),
                ('date_pred', models.DateField()),
                ('precision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nom_image', models.CharField(max_length=30)),
                ('classe_correcte', models.ForeignKey(blank=True, db_column='classe_correcte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_correcte', to='classifr.classe')),
                ('classe_predit', models.ForeignKey(db_column='classe_predit', on_delete=django.db.models.deletion.DO_NOTHING, related_name='classe_predit', to='classifr.classe')),
                ('nom_model', models.ForeignKey(db_column='nom_model', on_delete=django.db.models.deletion.DO_NOTHING, to='classifr.model')),
            ],
            options={
                'db_table': 'historique',
            },
        ),
    ]
